server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mkl2020/orderingsystem
          searchPaths:
          - config
          username: mkl2020
          password: mkl20200223github
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/